### PR TITLE
Added flag to choose if to render in top-bottom

### PR DESCRIPTION
**Pull request by GPaolo**
The rgb-array view can now be chosen if in top-bottom view or not.

### CODE REVIEW

**Comment by benelot** [comment]
Thanks for the PR. What is the use case of this?

**Comment by GPaolo** [comment]
In case you need a view of the robot from the top, centered on the initial position. It can be useful if you want to calculate the change/deplacement of the robot just from the image.

I needed it for my research and thought that it might be useful for other people as well.

**Comment by benelot** [comment]
I think it is a bit too specific for a certain use case. Isn't it easier to just move the camera along and keep it in sync with the robots position at all times?

**Comment by benelot** [comment]
I think I will not take this into my code base since it is overly specific and mixes in some additional part which is about coloring the model. However, I will probably take the color part sooner or later and show people how to visualize parts of the learning.

**Pull request closed without merging**
